version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    assignees:
      - "ukwhatn"
    groups:
      dev-dependencies:
        dependency-type: "development"
      testing:
        patterns:
          - "pytest*"
      linting:
        patterns:
          - "ruff"
          - "mypy"
    cooldown:
      default: 3
      patch: 1
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    assignees:
      - "ukwhatn"
    groups:
      github-actions:
        patterns:
          - "*"
